# Generated by Django 2.1 on 2018-12-21 09:35

import PersonApi.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('PersonId', models.AutoField(primary_key=True, serialize=False)),
                ('PersonName', models.CharField(max_length=30, verbose_name="person's first name")),
                ('Person_Image', models.ImageField(blank=True, null=True, upload_to=PersonApi.models.upload_file)),
                ('Person_sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'None')], max_length=1)),
                ('Person_BDate', models.DateField()),
                ('Person_CDate', models.DateField(auto_now_add=True)),
                ('UserName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
