# Generated by Django 2.1 on 2018-12-21 12:22

import PersonApi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonApi', '0002_auto_20181221_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Person_Image',
            field=models.FileField(blank=True, null=True, upload_to=PersonApi.models.upload_file),
        ),
    ]
