# Generated by Django 2.1 on 2018-12-21 11:42

import FileSecure.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PersonApi', '0002_auto_20181221_1709'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSecureEntry',
            fields=[
                ('File_ID', models.AutoField(primary_key=True, serialize=False)),
                ('File_Module', models.CharField(max_length=30, verbose_name='File Module Name')),
                ('File_Image', models.FileField(blank=True, null=True, upload_to=FileSecure.models.upload_file)),
                ('File_CDate', models.DateField(auto_now_add=True)),
                ('PersonNameID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PersonApi.Person')),
                ('UserNameID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
